# based on https://github.com/mvdan/github-actions-golang
# on: [push, pull_request]

name: ci
on: push
env:
  go-version: '1.23.x'
defaults:
  run:
    shell: sh
jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Go ${{ env.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # By default, actions/checkout will persist the GITHUB_TOKEN, so that further
        # steps in the job can perform authenticated git commands (that is: WRITE to
        # the repo). Following the Principle of least privilege, we disable this as long
        # as we don't need it.
        persist-credentials: false
        # Number of commits to fetch. Default: 1
        # We need to fetch more to find the latest tag, to create the version string.
        # In addition, "git describe" needs also "--tags", to let it find unannotated tags :-/
        fetch-depth: 20
        # Whether to fetch tags, even if fetch-depth > 0.
        fetch-tags: true

    - name: Build
      run: ./vis build

    - name: Test
      run: ./vis test --cover

    - name: vet
      if: matrix.os == 'ubuntu-latest'
      run: go vet ./...

    - name: staticcheck
      if: matrix.os == 'ubuntu-latest'
      uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
        install-go: false

    # See https://github.com/goreleaser/goreleaser-action
    # name: Make a release if we have seen a new tag
    # uses: goreleaser/goreleaser-action@v6
    # if: startsWith(github.ref, 'refs/tags/') <== nice trick
    # with:
    #   version: '~> v2'
    #   args: release --clean
    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}